### PR TITLE
Websphere Liberty fixes

### PR DESCRIPTION
**Pull request by mglantz**
Hi there,

Here are some fixes for the template, images stream was defined after buildconfig, which caused a failure when the push to OCP registry happened. Also some permissions missing for the Docker image. Also added a targetPort for the route, which were missing. Tested and works on OCP 3.4.

### CODE REVIEW

**Comment by mglantz** [comment]
Please note that the template currently points at my repo (have to use it for a demo tomorrow). Will point it back ASAP, or do it yourself :-)

**Comment by mglantz** [comment]
Hm, still something missing for the route. Fixing..

**Comment by mglantz** [comment]
OK, fixed, tried it a couple of times on fresh projects and fresh downloads of template. It's all good now, except for some additional permissions errors, which doesn't prevent things from coming up and displaying a nice webpage.

**Review by sebastianfaulhaber — APPROVED** [review]
All fine. Thanks a lot Markus!

**Pull request merged**
